name: FastAPI Microservices CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r user_service/requirements.txt
        pip install -r order_service/requirements.txt
        pip install -r gateway/requirements.txt
        pip install python-dotenv httpx psycopg2-binary fastapi uvicorn

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script_stop: false
        script: |
          cd ~/fastapi-microservice
          ./deploy.sh
        ssh_options: "-o StrictHostKeyChecking=no"


